# This is a build configuration for deployment through Atlassian's Bitbucket Pipelines.
# -----
# uses the node:18-alpine3.17 docker image and atlassian/rsync-deploy:0.8.1
# https://bitbucket.org/atlassian/rsync-deploy/src/master/
image: node:18-alpine3.17
clone:
  depth: 1
pipelines:
  branches:
    main:
      - step:
          name: Install and build ⚒️
          # cache node_modules for faster builds
          caches:
            - node
          # install, build and deploy
          script:
            # increase max memory heap
            - export NODE_OPTIONS=--max_old_space_size=4096
            - npm --version
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploy build folder to server using rsync 🚀
          clone:
              enabled: false
          deployment: production
          script:
            - pipe: atlassian/rsync-deploy:0.8.1
              variables:
                USER: 'periscopicclientsite'
                SERVER: 'clients.periscopic.com'
                REMOTE_PATH: '/home/periscopicclientsite/clients.periscopic.com/ab-c/adaptation-insights/develop/'
                LOCAL_PATH: 'dist/*'
                DEBUG: 'true'
                EXTRA_ARGS: '--archive --verbose --compress --progress'
                DELETE_FLAG: 'true'
    # review:
    #   - step:
    #       name: Install and build ⚒️
    #       # cache node_modules for faster builds
    #       caches:
    #         - node
    #       # install, build and deploy
    #       script:
    #         # increase max memory heap
    #         - export NODE_OPTIONS=--max_old_space_size=4096
    #         - npm --version
    #         - npm install
    #         - npm run build
    #       artifacts:
    #         - dist/**
    #   - step:
    #       name: Deploy build folder to server using rsync 🚀
    #       clone:
    #           enabled: false
    #       deployment: production
    #       script:
    #         - pipe: atlassian/rsync-deploy:0.8.1
    #           variables:
    #             USER: 'periscopicclientsite'
    #             SERVER: 'clients.periscopic.com'
    #             REMOTE_PATH: '/home/periscopicclientsite/clients.periscopic.com/dartmouth_ctl/dartmouth_ctl_client/dev/latest/'
    #             LOCAL_PATH: 'dist/*'
    #             DEBUG: 'true'
    #             EXTRA_ARGS: '--archive --verbose --compress --progress'
    #             DELETE_FLAG: 'true'


